CREATE USER 'htwow'@'localhost' IDENTIFIED BY 'htwow' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0;

GRANT USAGE ON *.* TO 'htwow'@'localhost';

CREATE DATABASE `htwow` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL PRIVILEGES ON `htwow`.* TO 'htwow'@'localhost' WITH GRANT OPTION;
